### ISSUE TITLE
verifierStorage protobuf

### ISSUE THREAD

**Issue by SoujanyaPonnapalli** [RainBlock/rainblock-protocol#20]
If an account is deleted and re-created by the transactions within the same block with new code, the UpdateOp is similar to modifying an existing account's code. Is this okay?

```
// Used for each update to the node's merkle tree.
message UpdateOp {
  bytes account = 1; // 20 bytes, BE account number
  bytes balance = 2; //  32 bytes, BE new balance. May not be present if the balance is unchanged.
  uint32 updates = 3; // Increment by one for each nonce update. May not be present if the nonce is unchanged.
  repeated StorageUpdate storage_update = 4; // Storage updates, if any.
  bytes code = 5; // Code bytes, only applicable for creation of a contract account.
  bool deleted = 6; // Set if the account was deleted. All other fields, if present, are ignored.
}
```

Also, if the previous account had nonce n; and we delete the account and create a new account with the same address: how will the nonce be set to 0 for the new account if all that the verifier is sending are updates?

**Comment by no2chem** [comment]
Because a contract account address is created with the nonce of the creator, technically a contract could not be recreated at the same address after being deleted.

Other than a collision, there's only one rare edge case where someone manages to create a normal account at the same address as a previous contract account. I guess we could just send the full nonce every time, which would resolve this issue. You could open a PR if you want to change `uint32 updates` to `uint64 nonce`

**Comment by SoujanyaPonnapalli** [comment]
Okay I'll open a PR for having nonce. Also, if code is sent by the verifier: the storage node updates the code. Verifier will take care of not initializing the code after the account is created. Does that sound good?

**Comment by no2chem** [comment]
Sure. The verifier will send code only during creation.
